"""
Report Generator - Creates beautiful Markdown and HTML reports
Part of the Agentic RnD Tool multi-agent framework
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional
import json


class ReportGenerator:
    """
    Generates formatted reports from agent results
    """
    
    def __init__(self, output_dir: str = "./reports"):
        """
        Initialize report generator
        
        Args:
            output_dir: Directory to save reports
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)
    
    def generate_markdown_report(self, results: Dict, filename: Optional[str] = None) -> str:
        """
        Generate a comprehensive Markdown report
        
        Args:
            results: Results dictionary from orchestrator
            filename: Optional custom filename
            
        Returns:
            Path to generated report
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.md"
        
        report_path = self.output_dir / filename
        
        # Build markdown content
        markdown = self._build_markdown(results)
        
        # Write to file
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(markdown)
        
        return str(report_path)
    
    def _build_markdown(self, results: Dict) -> str:
        """Build markdown content from results"""
        
        task = results.get('task', 'Unknown Task')
        timestamp = results.get('timestamp', datetime.now().isoformat())
        summary = results.get('summary', '')
        agents_used = results.get('agents_used', [])
        data = results.get('data', {})
        
        # Header
        md = f"""# Agentic RnD Tool - Research Report

**Generated:** {timestamp}  
**Task:** {task}

---

## 📊 Executive Summary

{summary}

**Agents Deployed:** {', '.join(agents_used)}

---

"""
        
        # Research Results Section
        if 'research' in data:
            md += self._build_research_section(data['research'], results.get('raw_results', {}).get('web_research', {}))
        
        # Security Results Section
        if 'security' in data:
            md += self._build_security_section(data['security'], results.get('raw_results', {}).get('security_scan', {}))
        
        # Footer
        md += f"""
---

## 📝 Report Metadata

- **Created By:** Akash Rathod
- **Generated By:** Agentic RnD Tool v1.0.0
- **Framework:** OpenClaw Multi-Agent Orchestration
- **Timestamp:** {timestamp}
- **Report Format:** Markdown

---

*This report was automatically generated by the Agentic RnD Tool framework.*
*Created by Akash Rathod*
"""
        
        return md
    
    def _build_research_section(self, research_data: Dict, raw_data: Dict) -> str:
        """Build research results section"""
        
        sources = research_data.get('sources_scraped', 0)
        items = research_data.get('content_items', 0)
        
        md = f"""## 🔍 Research Results

### Overview
- **Sources Scraped:** {sources}
- **Content Items:** {items}
- **Success Rate:** {(sources/max(sources, 1)*100):.1f}%

### Content Analysis

"""
        
        # Add sample content if available
        content = raw_data.get('content', [])
        if content:
            md += "#### Scraped Pages:\n\n"
            for i, item in enumerate(content[:10], 1):  # First 10 items
                title = item.get('title', 'Untitled')
                url = item.get('url', '')
                content_size = len(item.get('content', ''))
                summary = item.get('summary', '')
                is_summarized = item.get('summarized', False)
                
                md += f"{i}. **{title}**\n"
                md += f"   - URL: {url}\n"
                md += f"   - Content Size: {content_size} chars\n"
                md += f"   - Status: {item.get('status_code', 'N/A')}\n"
                
                # Add AI summary if available
                if summary and is_summarized:
                    md += f"   - **🤖 AI Summary:** {summary}\n"
                
                md += "\n"
            
            if len(content) > 10:
                md += f"*... and {len(content) - 10} more pages*\n\n"
        
        # Summary
        summary = raw_data.get('summary', '')
        if summary:
            md += f"### Summary\n\n{summary}\n\n"
        
        # Failed URLs
        failed = raw_data.get('failed_urls', [])
        if failed:
            md += f"### ⚠️ Failed URLs ({len(failed)})\n\n"
            for fail in failed[:5]:
                md += f"- {fail.get('url', 'Unknown')} - Error: {fail.get('error', 'Unknown')}\n"
            md += "\n"
        
        return md + "---\n\n"
    
    def _build_security_section(self, security_data: Dict, raw_data: Dict) -> str:
        """Build security results section"""
        
        alerts = security_data.get('alerts', 0)
        summary = security_data.get('summary', {})
        
        md = f"""## 🔒 Security Assessment

### Overview
- **Total Alerts:** {alerts}
- **Critical:** {summary.get('critical', 0)}
- **High:** {summary.get('high', 0)}
- **Medium:** {summary.get('medium', 0)}
- **Low:** {summary.get('low', 0)}
- **Informational:** {summary.get('informational', 0)}

### Risk Assessment

"""
        
        # Risk level indicator
        critical = summary.get('critical', 0)
        high = summary.get('high', 0)
        
        if critical > 0:
            risk_level = "🔴 CRITICAL"
        elif high > 0:
            risk_level = "🟠 HIGH"
        elif summary.get('medium', 0) > 0:
            risk_level = "🟡 MEDIUM"
        else:
            risk_level = "🟢 LOW"
        
        md += f"**Overall Risk Level:** {risk_level}\n\n"
        
        # Alert details
        alert_list = raw_data.get('alerts', [])
        if alert_list:
            md += "### Findings\n\n"
            
            # Group by risk level
            by_risk = {}
            for alert in alert_list:
                risk = alert.get('risk', 'Unknown')
                if risk not in by_risk:
                    by_risk[risk] = []
                by_risk[risk].append(alert)
            
            # Display by severity
            for risk_level in ['High', 'Medium', 'Low', 'Informational']:
                if risk_level in by_risk:
                    md += f"#### {risk_level} Risk Issues\n\n"
                    for alert in by_risk[risk_level]:
                        md += f"- **{alert.get('name', 'Unknown Issue')}**\n"
                        md += f"  - Confidence: {alert.get('confidence', 'N/A')}\n"
                        md += f"  - URL: {alert.get('url', 'N/A')}\n"
                        if alert.get('solution'):
                            md += f"  - Solution: {alert.get('solution')}\n"
                        md += "\n"
        
        return md + "---\n\n"
    
    def generate_json_report(self, results: Dict, filename: Optional[str] = None) -> str:
        """
        Generate JSON report (already have this, but format nicely)
        
        Args:
            results: Results dictionary
            filename: Optional custom filename
            
        Returns:
            Path to generated report
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.json"
        
        report_path = self.output_dir / filename
        
        with open(report_path, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2, ensure_ascii=False)
        
        return str(report_path)
    
    def generate_html_report(self, results: Dict, filename: Optional[str] = None) -> str:
        """
        Generate interactive HTML dashboard report
        
        Args:
            results: Results dictionary from orchestrator
            filename: Optional custom filename
            
        Returns:
            Path to generated HTML report
        """
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.html"
        
        report_path = self.output_dir / filename
        
        # Build HTML content
        html = self._build_html(results)
        
        # Write to file
        with open(report_path, 'w', encoding='utf-8') as f:
            f.write(html)
        
        return str(report_path)
    
    def _build_html(self, results: Dict) -> str:
        """Build interactive HTML dashboard"""
        
        task = results.get('task', 'Unknown Task')
        timestamp = results.get('timestamp', datetime.now().isoformat())
        summary = results.get('summary', '')
        agents_used = results.get('agents_used', [])
        data = results.get('data', {})
        
        # Extract research data
        research_sources = 0
        research_items = 0
        research_content = []
        if 'research' in data:
            research_sources = data['research'].get('sources_scraped', 0)
            research_items = data['research'].get('content_items', 0)
            raw_research = results.get('raw_results', {}).get('web_research', {})
            research_content = raw_research.get('content', [])
        
        # Extract security data
        security_alerts = 0
        security_summary = {}
        security_details = []
        if 'security' in data:
            security_alerts = data['security'].get('alerts', 0)
            security_summary = data['security'].get('summary', {})
            raw_security = results.get('raw_results', {}).get('security_scan', {})
            security_details = raw_security.get('alerts', [])
        
        # Build content cards HTML
        content_cards = ""
        for i, item in enumerate(research_content[:20], 1):
            title = item.get('title', 'Untitled')
            url = item.get('url', '')
            content_size = len(item.get('content', ''))
            status = item.get('status_code', 'N/A')
            summary = item.get('summary', '')
            is_summarized = item.get('summarized', False)
            
            # Build summary section if available
            summary_html = ""
            if summary and is_summarized:
                summary_html = f"""
                <div class="ai-summary mt-3 p-3" style="background: linear-gradient(135deg, rgba(167, 139, 250, 0.1), rgba(139, 92, 246, 0.1)); border-left: 3px solid #a78bfa; border-radius: 8px;">
                    <div class="d-flex align-items-center mb-2">
                        <i class="bi bi-robot" style="font-size: 1.2rem; color: #a78bfa; margin-right: 8px;"></i>
                        <small class="fw-bold" style="color: #7c3aed;">AI Summary</small>
                    </div>
                    <p class="small mb-0" style="color: #4c1d95; line-height: 1.6;">{summary[:300]}</p>
                </div>
                """
            
            content_cards += f"""
            <div class="col-md-6">
                <div class="content-card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-start mb-3">
                            <span class="badge badge-custom badge-info-custom">#{i}</span>
                            <div>
                                {f'<span class="badge" style="background: linear-gradient(135deg, #a78bfa, #7c3aed); margin-right: 5px;"><i class="bi bi-stars"></i> AI</span>' if is_summarized else ''}
                                <span class="badge badge-custom badge-success-custom">
                                    <i class="bi bi-check-circle"></i> {status}
                                </span>
                            </div>
                        </div>
                        <h6 class="card-title">{title[:80]}</h6>
                        <a href="{url}" target="_blank" class="content-link">
                            <i class="bi bi-link-45deg"></i> {url[:55]}...
                        </a>
                        {summary_html}
                        <div class="d-flex justify-content-between align-items-center mt-3">
                            <small class="text-muted">
                                <i class="bi bi-file-text"></i> {content_size:,} characters
                            </small>
                            <a href="{url}" target="_blank" class="btn btn-sm btn-outline-primary">
                                <i class="bi bi-box-arrow-up-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            """
        
        # Build security alerts HTML
        security_cards = ""
        for alert in security_details[:10]:
            risk = alert.get('risk', 'Unknown')
            risk_color = {
                'High': 'danger',
                'Medium': 'warning',
                'Low': 'info',
                'Informational': 'secondary'
            }.get(risk, 'secondary')
            
            security_cards += f"""
            <div class="col-md-6">
                <div class="security-card border-{risk_color}">
                    <div class="card-header bg-{risk_color} bg-opacity-10 text-{risk_color}">
                        <div class="d-flex justify-content-between align-items-center">
                            <strong><i class="bi bi-shield-exclamation"></i> {alert.get('name', 'Unknown Issue')[:50]}</strong>
                            <span class="badge bg-{risk_color}">{risk}</span>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="mb-2">
                            <small class="text-muted"><i class="bi bi-graph-up"></i> <strong>Confidence:</strong></small>
                            <span class="ms-2">{alert.get('confidence', 'N/A')}</span>
                        </div>
                        <div class="mb-2">
                            <small class="text-muted"><i class="bi bi-link-45deg"></i> <strong>URL:</strong></small>
                            <p class="small mb-0 text-break">{alert.get('url', 'N/A')[:80]}</p>
                        </div>
                        <p class="card-text small text-muted">{alert.get('url', 'N/A')[:80]}</p>
                    </div>
                </div>
            </div>
            """
        
        # Build complete HTML
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agentic RnD Tool - Research Report</title>
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Fira+Code:wght@400;500&display=swap" rel="stylesheet">
    
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    
    <!-- Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
    
    <!-- AOS Animation Library -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    
    <style>
        :root {{
            --primary-gradient: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            --success-gradient: linear-gradient(135deg, #11998e 0%, #38ef7d 100%);
            --danger-gradient: linear-gradient(135deg, #eb3349 0%, #f45c43 100%);
            --info-gradient: linear-gradient(135deg, #4facfe 0%, #00f2fe 100%);
            --warning-gradient: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
            
            --primary-color: #667eea;
            --success-color: #11998e;
            --info-color: #4facfe;
            --warning-color: #f093fb;
            --danger-color: #eb3349;
            
            --text-primary: #2d3748;
            --text-secondary: #718096;
            --bg-light: #f7fafc;
            --border-color: #e2e8f0;
            
            --shadow-sm: 0 2px 8px rgba(0, 0, 0, 0.08);
            --shadow-md: 0 4px 16px rgba(0, 0, 0, 0.12);
            --shadow-lg: 0 10px 40px rgba(0, 0, 0, 0.15);
            --shadow-xl: 0 20px 60px rgba(0, 0, 0, 0.2);
        }}
        
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            background-attachment: fixed;
            min-height: 100vh;
            padding: 40px 20px;
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            color: var(--text-primary);
            overflow-x: hidden;
        }}
        
        /* Animated Background Pattern */
        body::before {{
            content: '';
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: 
                radial-gradient(circle at 20% 50%, rgba(255, 255, 255, 0.1) 0%, transparent 50%),
                radial-gradient(circle at 80% 80%, rgba(255, 255, 255, 0.1) 0%, transparent 50%);
            pointer-events: none;
            z-index: 0;
        }}
        
        .container {{
            position: relative;
            z-index: 1;
        }}
        
        .dashboard-container {{
            background: rgba(255, 255, 255, 0.98);
            backdrop-filter: blur(20px);
            border-radius: 24px;
            box-shadow: var(--shadow-xl);
            overflow: hidden;
            border: 1px solid rgba(255, 255, 255, 0.5);
        }}
        
        /* Header Section */
        .header-section {{
            background: var(--primary-gradient);
            color: white;
            padding: 60px 40px;
            position: relative;
            overflow: hidden;
        }}
        
        .header-section::before {{
            content: '';
            position: absolute;
            top: -50%;
            right: -10%;
            width: 500px;
            height: 500px;
            background: radial-gradient(circle, rgba(255, 255, 255, 0.1) 0%, transparent 70%);
            border-radius: 50%;
            animation: float 20s ease-in-out infinite;
        }}
        
        .header-section::after {{
            content: '';
            position: absolute;
            bottom: -30%;
            left: -5%;
            width: 400px;
            height: 400px;
            background: radial-gradient(circle, rgba(255, 255, 255, 0.08) 0%, transparent 70%);
            border-radius: 50%;
            animation: float 25s ease-in-out infinite reverse;
        }}
        
        @keyframes float {{
            0%, 100% {{ transform: translate(0, 0) rotate(0deg); }}
            33% {{ transform: translate(30px, -30px) rotate(120deg); }}
            66% {{ transform: translate(-20px, 20px) rotate(240deg); }}
        }}
        
        .header-section .content {{
            position: relative;
            z-index: 2;
        }}
        
        .header-icon {{
            font-size: 4rem;
            animation: pulse 3s ease-in-out infinite;
            display: inline-block;
            margin-bottom: 20px;
        }}
        
        @keyframes pulse {{
            0%, 100% {{ transform: scale(1); opacity: 1; }}
            50% {{ transform: scale(1.1); opacity: 0.9; }}
        }}
        
        .display-3 {{
            font-weight: 800;
            letter-spacing: -0.02em;
            text-shadow: 0 2px 20px rgba(0, 0, 0, 0.2);
        }}
        
        .subtitle {{
            font-size: 1.25rem;
            font-weight: 500;
            opacity: 0.95;
            margin-top: 10px;
        }}
        
        .tech-badge {{
            display: inline-block;
            background: rgba(255, 255, 255, 0.2);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.3);
            padding: 8px 20px;
            border-radius: 50px;
            font-size: 0.9rem;
            font-weight: 500;
            margin-top: 15px;
            transition: all 0.3s ease;
        }}
        
        .tech-badge:hover {{
            background: rgba(255, 255, 255, 0.3);
            transform: translateY(-2px);
        }}
        
        /* Task Info Section */
        .task-info-section {{
            padding: 30px 40px;
            background: linear-gradient(to right, #f8f9fa, #ffffff);
            border-bottom: 1px solid var(--border-color);
        }}
        
        .task-card {{
            background: white;
            border-radius: 16px;
            padding: 25px;
            box-shadow: var(--shadow-sm);
            border-left: 4px solid var(--primary-color);
        }}
        
        .task-label {{
            color: var(--text-secondary);
            font-size: 0.875rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-bottom: 10px;
        }}
        
        .task-value {{
            font-family: 'Fira Code', monospace;
            font-size: 1rem;
            color: var(--text-primary);
            word-break: break-all;
        }}
        
        .meta-badge {{
            background: linear-gradient(135deg, #667eea15, #764ba215);
            color: var(--primary-color);
            padding: 6px 16px;
            border-radius: 20px;
            font-size: 0.875rem;
            font-weight: 600;
            border: 1px solid rgba(102, 126, 234, 0.2);
        }}
        
        /* Stats Cards */
        .stats-section {{
            padding: 40px;
        }}
        
        .stat-card {{
            background: white;
            border-radius: 20px;
            padding: 30px;
            box-shadow: var(--shadow-md);
            border: 1px solid var(--border-color);
            position: relative;
            overflow: hidden;
            transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
            height: 100%;
        }}
        
        .stat-card::before {{
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 5px;
            height: 100%;
            background: var(--primary-gradient);
            transition: width 0.3s ease;
        }}
        
        .stat-card:hover {{
            transform: translateY(-8px);
            box-shadow: var(--shadow-lg);
        }}
        
        .stat-card:hover::before {{
            width: 100%;
            opacity: 0.05;
        }}
        
        .stat-card.research-card::before {{
            background: var(--info-gradient);
        }}
        
        .stat-card.security-card::before {{
            background: var(--danger-gradient);
        }}
        
        .stat-icon {{
            width: 60px;
            height: 60px;
            background: var(--primary-gradient);
            border-radius: 16px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1.8rem;
            color: white;
            box-shadow: var(--shadow-md);
            margin-bottom: 20px;
        }}
        
        .stat-icon.research-icon {{
            background: var(--info-gradient);
        }}
        
        .stat-icon.security-icon {{
            background: var(--danger-gradient);
        }}
        
        .stat-number {{
            font-size: 3rem;
            font-weight: 800;
            color: var(--text-primary);
            line-height: 1;
            margin-bottom: 10px;
        }}
        
        .stat-label {{
            color: var(--text-secondary);
            font-size: 0.875rem;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }}
        
        .stat-meta {{
            margin-top: 20px;
            padding-top: 20px;
            border-top: 1px solid var(--border-color);
        }}
        
        .stat-meta-item {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 8px 0;
            font-size: 0.9rem;
        }}
        
        .stat-meta-item .label {{
            color: var(--text-secondary);
            font-weight: 500;
        }}
        
        .stat-meta-item .value {{
            font-weight: 700;
            color: var(--text-primary);
        }}
        
        /* Summary Alert */
        .summary-section {{
            padding: 0 40px 40px;
        }}
        
        .summary-alert {{
            background: linear-gradient(135deg, #11998e15, #38ef7d15);
            border: 2px solid #11998e40;
            border-radius: 16px;
            padding: 25px 30px;
            position: relative;
            overflow: hidden;
        }}
        
        .summary-alert::before {{
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 6px;
            height: 100%;
            background: var(--success-gradient);
        }}
        
        .summary-icon {{
            font-size: 2rem;
            color: var(--success-color);
            margin-right: 15px;
        }}
        
        .summary-text {{
            font-size: 1.1rem;
            color: var(--text-primary);
            font-weight: 500;
            line-height: 1.6;
        }}
        
        /* Tabs */
        .tabs-section {{
            padding: 0 40px 40px;
        }}
        
        .nav-pills .nav-link {{
            border-radius: 12px;
            padding: 12px 24px;
            font-weight: 600;
            color: var(--text-secondary);
            transition: all 0.3s ease;
            margin-right: 10px;
            border: 2px solid transparent;
        }}
        
        .nav-pills .nav-link:hover {{
            background: linear-gradient(135deg, #667eea15, #764ba215);
            color: var(--primary-color);
        }}
        
        .nav-pills .nav-link.active {{
            background: var(--primary-gradient);
            color: white;
            box-shadow: var(--shadow-md);
        }}
        
        .tab-content {{
            padding: 30px 0;
        }}
        
        /* Search Box */
        .search-wrapper {{
            position: relative;
            margin-bottom: 30px;
        }}
        
        .search-box {{
            width: 100%;
            padding: 15px 50px 15px 20px;
            border: 2px solid var(--border-color);
            border-radius: 50px;
            font-size: 1rem;
            transition: all 0.3s ease;
            background: white;
        }}
        
        .search-box:focus {{
            outline: none;
            border-color: var(--primary-color);
            box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.1);
        }}
        
        .search-icon {{
            position: absolute;
            right: 20px;
            top: 50%;
            transform: translateY(-50%);
            color: var(--text-secondary);
            font-size: 1.2rem;
        }}
        
        /* Content Cards */
        .content-card {{
            background: white;
            border-radius: 16px;
            overflow: hidden;
            box-shadow: var(--shadow-sm);
            border: 1px solid var(--border-color);
            transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
            height: 100%;
        }}
        
        .content-card:hover {{
            transform: translateY(-5px);
            box-shadow: var(--shadow-md);
            border-color: var(--primary-color);
        }}
        
        .content-card .card-body {{
            padding: 25px;
        }}
        
        .content-card .card-title {{
            font-weight: 700;
            font-size: 1rem;
            color: var(--text-primary);
            margin-bottom: 15px;
            line-height: 1.4;
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
            overflow: hidden;
        }}
        
        .content-link {{
            color: var(--primary-color);
            text-decoration: none;
            font-size: 0.875rem;
            display: block;
            margin-bottom: 15px;
            transition: color 0.2s ease;
        }}
        
        .content-link:hover {{
            color: #764ba2;
            text-decoration: underline;
        }}
        
        .badge-custom {{
            padding: 6px 14px;
            border-radius: 8px;
            font-size: 0.8rem;
            font-weight: 600;
        }}
        
        .badge-info-custom {{
            background: linear-gradient(135deg, #4facfe15, #00f2fe15);
            color: var(--info-color);
            border: 1px solid rgba(79, 172, 254, 0.3);
        }}
        
        .badge-success-custom {{
            background: linear-gradient(135deg, #11998e15, #38ef7d15);
            color: var(--success-color);
            border: 1px solid rgba(17, 153, 142, 0.3);
        }}
        
        /* Security Cards */
        .security-card {{
            background: white;
            border-radius: 16px;
            overflow: hidden;
            box-shadow: var(--shadow-sm);
            transition: all 0.3s ease;
            height: 100%;
        }}
        
        .security-card.border-danger {{
            border-left: 4px solid var(--danger-color);
        }}
        
        .security-card.border-warning {{
            border-left: 4px solid var(--warning-color);
        }}
        
        .security-card.border-info {{
            border-left: 4px solid var(--info-color);
        }}
        
        .security-card:hover {{
            transform: translateY(-5px);
            box-shadow: var(--shadow-md);
        }}
        
        .security-card .card-header {{
            font-weight: 700;
            padding: 15px 20px;
            border-bottom: 1px solid var(--border-color);
        }}
        
        .security-card .card-body {{
            padding: 20px;
        }}
        
        /* Chart Container */
        .chart-container {{
            background: white;
            border-radius: 16px;
            padding: 25px;
            box-shadow: var(--shadow-sm);
            border: 1px solid var(--border-color);
        }}
        
        /* Raw Data */
        .raw-data-container {{
            background: #1e293b;
            border-radius: 16px;
            padding: 30px;
            box-shadow: var(--shadow-lg);
            max-height: 600px;
            overflow-y: auto;
        }}
        
        .raw-data-container::-webkit-scrollbar {{
            width: 10px;
        }}
        
        .raw-data-container::-webkit-scrollbar-track {{
            background: #0f172a;
            border-radius: 10px;
        }}
        
        .raw-data-container::-webkit-scrollbar-thumb {{
            background: #475569;
            border-radius: 10px;
        }}
        
        .raw-data-container::-webkit-scrollbar-thumb:hover {{
            background: #64748b;
        }}
        
        .raw-data-container pre {{
            margin: 0;
            color: #e2e8f0;
            font-family: 'Fira Code', monospace;
            font-size: 0.875rem;
            line-height: 1.6;
        }}
        
        .raw-data-container code {{
            color: inherit;
        }}
        
        /* Footer */
        .footer-section {{
            padding: 30px 40px;
            background: linear-gradient(to right, #f8f9fa, #ffffff);
            border-top: 1px solid var(--border-color);
            text-align: center;
        }}
        
        .footer-text {{
            color: var(--text-secondary);
            font-size: 0.875rem;
            margin: 0;
            line-height: 1.6;
        }}
        
        .footer-link {{
            color: var(--primary-color);
            text-decoration: none;
            font-weight: 600;
            transition: color 0.2s ease;
        }}
        
        .footer-link:hover {{
            color: #764ba2;
        }}
        
        /* Responsive Design */
        @media (max-width: 768px) {{
            body {{
                padding: 20px 10px;
            }}
            
            .header-section {{
                padding: 40px 20px;
            }}
            
            .stats-section,
            .summary-section,
            .tabs-section {{
                padding: 20px;
            }}
            
            .task-info-section {{
                padding: 20px;
            }}
            
            .stat-number {{
                font-size: 2.5rem;
            }}
            
            .nav-pills .nav-link {{
                margin-bottom: 10px;
                margin-right: 5px;
                padding: 10px 16px;
            }}
        }}
        
        /* Loading Animation */
        @keyframes shimmer {{
            0% {{ background-position: -1000px 0; }}
            100% {{ background-position: 1000px 0; }}
        }}
        
        .loading {{
            animation: shimmer 2s infinite;
            background: linear-gradient(to right, #f6f7f8 0%, #edeef1 20%, #f6f7f8 40%, #f6f7f8 100%);
            background-size: 1000px 100%;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="dashboard-container" data-aos="fade-up">
            <!-- Header -->
            <div class="header-section text-center">
                <div class="content">
                    <div class="header-icon">
                        <i class="bi bi-robot"></i>
                    </div>
                    <h1 class="display-3 mb-3">Agentic RnD Tool</h1>
                    <p class="subtitle">Multi-Agent Research & Security Framework</p>
                    <span class="tech-badge">
                        <i class="bi bi-diagram-3"></i> Powered by OpenClaw Orchestration
                    </span>
                </div>
            </div>
            
            <!-- Task Info -->
            <div class="task-info-section" data-aos="fade-up" data-aos-delay="100">
                <div class="row align-items-center">
                    <div class="col-md-8 mb-3 mb-md-0">
                        <div class="task-card">
                            <div class="task-label">
                                <i class="bi bi-bullseye"></i> Target Task
                            </div>
                            <div class="task-value">{task}</div>
                        </div>
                    </div>
                    <div class="col-md-4 text-end">
                        <div class="mb-3">
                            <span class="meta-badge">
                                <i class="bi bi-calendar3"></i> {timestamp[:10]}
                            </span>
                        </div>
                        <div>
                            <span class="meta-badge">
                                <i class="bi bi-cpu"></i> {', '.join(agents_used)}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
                        <p class="mb-0">
                            <span class="badge bg-success">{', '.join(agents_used)}</span>
                        </p>
                    </div>
                </div>
            </div>
            
            <!-- Stats Cards -->
            <div class="stats-section" data-aos="fade-up" data-aos-delay="200">
                <div class="row g-4">
                    <div class="col-md-6">
                        <div class="stat-card research-card">
                            <div class="stat-icon research-icon">
                                <i class="bi bi-search"></i>
                            </div>
                            <div class="stat-number">{research_sources}</div>
                            <div class="stat-label">Sources Scraped</div>
                            <div class="stat-meta">
                                <div class="stat-meta-item">
                                    <span class="label">
                                        <i class="bi bi-file-text"></i> Content Items
                                    </span>
                                    <span class="value">{research_items}</span>
                                </div>
                                <div class="stat-meta-item">
                                    <span class="label">
                                        <i class="bi bi-check-circle"></i> Success Rate
                                    </span>
                                    <span class="value">100%</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    {"" if security_alerts == 0 else f'''
                    <div class="col-md-6" data-aos="fade-up" data-aos-delay="300">
                        <div class="stat-card security-card">
                            <div class="stat-icon security-icon">
                                <i class="bi bi-shield-exclamation"></i>
                            </div>
                            <div class="stat-number">{security_alerts}</div>
                            <div class="stat-label">Security Alerts</div>
                            <div class="stat-meta">
                                <div class="stat-meta-item">
                                    <span class="label">
                                        <i class="bi bi-exclamation-octagon-fill text-danger"></i> Critical
                                    </span>
                                    <span class="value">{security_summary.get('critical', 0)}</span>
                                </div>
                                <div class="stat-meta-item">
                                    <span class="label">
                                        <i class="bi bi-exclamation-triangle-fill text-warning"></i> High
                                    </span>
                                    <span class="value">{security_summary.get('high', 0)}</span>
                                </div>
                                <div class="stat-meta-item">
                                    <span class="label">
                                        <i class="bi bi-info-circle-fill text-info"></i> Medium
                                    </span>
                                    <span class="value">{security_summary.get('medium', 0)}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    '''}
                </div>
            </div>
            
            <!-- Summary -->
            <div class="summary-section" data-aos="fade-up" data-aos-delay="400">
                <div class="summary-alert d-flex align-items-center">
                    <div class="summary-icon">
                        <i class="bi bi-check-circle-fill"></i>
                    </div>
                    <div class="summary-text flex-grow-1">
                        {summary}
                        <br>
                        <small class="text-muted mt-2 d-block">
                            <i class="bi bi-cpu"></i> Agents: <strong>{', '.join(agents_used)}</strong>
                        </small>
                    </div>
                </div>
            </div>
            
            <!-- Tabs -->
            <div class="tabs-section" data-aos="fade-up" data-aos-delay="500">
                <ul class="nav nav-pills mb-3" id="reportTabs" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active" id="research-tab" data-bs-toggle="pill" 
                                data-bs-target="#research" type="button" role="tab">
                            <i class="bi bi-file-earmark-text"></i> Research ({research_items})
                        </button>
                    </li>
                    {"" if security_alerts == 0 else f'''
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="security-tab" data-bs-toggle="pill" 
                                data-bs-target="#security" type="button" role="tab">
                            <i class="bi bi-shield-fill-check"></i> Security ({security_alerts})
                        </button>
                    </li>
                    '''}
                    <li class="nav-item" role="presentation">
                        <button class="nav-link" id="raw-tab" data-bs-toggle="pill" 
                                data-bs-target="#raw" type="button" role="tab">
                            <i class="bi bi-braces"></i> Raw Data
                        </button>
                    </li>
                </ul>
                
                <div class="tab-content" id="reportTabsContent">
                    <!-- Research Tab -->
                    <div class="tab-pane fade show active" id="research" role="tabpanel">
                        <div class="search-wrapper">
                            <input type="text" id="searchContent" class="search-box" 
                                   placeholder="Search content by title, URL, or keywords...">
                            <i class="bi bi-search search-icon"></i>
                        </div>
                        
                        <div class="row g-3" id="contentGrid">
                            {content_cards if content_cards else '<div class="col-12"><div class="text-center text-muted py-5"><i class="bi bi-inbox" style="font-size: 3rem;"></i><p class="mt-3">No research content available</p></div></div>'}
                        </div>
                        
                        {f'<div class="text-center mt-4"><span class="meta-badge"><i class="bi bi-info-circle"></i> Showing 20 of {len(research_content)} results</span></div>' if len(research_content) > 20 else ''}
                    </div>
                    
                    <!-- Security Tab -->
                    {"" if security_alerts == 0 else f'''
                    <div class="tab-pane fade" id="security" role="tabpanel">
                        <div class="row mb-4 g-4">
                            <div class="col-md-6">
                                <div class="chart-container">
                                    <h5 class="mb-3"><i class="bi bi-pie-chart"></i> Risk Distribution</h5>
                                    <canvas id="riskChart"></canvas>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="chart-container">
                                    <h5 class="mb-3"><i class="bi bi-list-check"></i> Risk Summary</h5>
                                    <div class="list-group list-group-flush">
                                        <div class="list-group-item d-flex justify-content-between align-items-center border-0 px-0">
                                            <span><i class="bi bi-exclamation-octagon-fill text-danger"></i> Critical</span>
                                            <span class="badge bg-danger rounded-pill">{security_summary.get('critical', 0)}</span>
                                        </div>
                                        <div class="list-group-item d-flex justify-content-between align-items-center border-0 px-0">
                                            <span><i class="bi bi-exclamation-triangle-fill text-warning"></i> High</span>
                                            <span class="badge bg-warning rounded-pill">{security_summary.get('high', 0)}</span>
                                        </div>
                                        <div class="list-group-item d-flex justify-content-between align-items-center border-0 px-0">
                                                <span><i class="bi bi-info-circle text-info"></i> Medium</span>
                                                <strong>{security_summary.get('medium', 0)}</strong>
                                            </li>
                                            <li class="list-group-item d-flex justify-content-between">
                                                <span><i class="bi bi-info text-secondary"></i> Low</span>
                                                <strong>{security_summary.get('low', 0)}</strong>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <h5 class="mb-3">Security Findings</h5>
                        <div class="row">
                            {security_cards if security_cards else '<div class="col-12"><p class="text-muted">No security findings</p></div>'}
                        </div>
                    </div>
                    '''}
                    
                    <!-- Raw Data Tab -->
                    <div class="tab-pane fade" id="raw" role="tabpanel">
                        <pre class="bg-dark text-light p-4 rounded"><code>{json.dumps(results, indent=2, ensure_ascii=False)}</code></pre>
                    </div>
                </div>
            </div>
            
            <!-- Footer -->
            <div class="footer-section">
                <p class="footer-text">
                    <i class="bi bi-person-circle"></i> Created by <strong class="footer-link">Akash Rathod</strong>
                    <br>
                    <i class="bi bi-robot"></i> Generated by <strong class="footer-link">Agentic RnD Tool v1.0.0</strong>
                    <br>
                    <i class="bi bi-diagram-3"></i> Powered by OpenClaw Multi-Agent Framework
                    <br>
                    <small><i class="bi bi-calendar3"></i> {timestamp}</small>
                </p>
            </div>
        </div>
    </div>
    
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
    <!-- Custom JavaScript -->
    <script>
        // Initialize AOS animations
        AOS.init({{
            duration: 800,
            easing: 'ease-in-out',
            once: true,
            offset: 100
        }});
        
        // Search functionality with debounce
        let searchTimeout;
        document.getElementById('searchContent')?.addEventListener('input', function(e) {{
            clearTimeout(searchTimeout);
            searchTimeout = setTimeout(() => {{
                const searchTerm = e.target.value.toLowerCase();
                const cards = document.querySelectorAll('#contentGrid > div');
                let visibleCount = 0;
                
                cards.forEach(card => {{
                    const text = card.textContent.toLowerCase();
                    const shouldShow = text.includes(searchTerm);
                    card.style.display = shouldShow ? '' : 'none';
                    if (shouldShow) visibleCount++;
                }});
                
                // Show "no results" message if needed
                if (visibleCount === 0 && searchTerm) {{
                    const noResults = document.getElementById('noResults');
                    if (!noResults) {{
                        const msg = document.createElement('div');
                        msg.id = 'noResults';
                        msg.className = 'col-12 text-center text-muted py-5';
                        msg.innerHTML = '<i class="bi bi-search" style="font-size: 3rem;"></i><p class="mt-3">No results found for "' + searchTerm + '"</p>';
                        document.getElementById('contentGrid').appendChild(msg);
                    }}
                }} else {{
                    document.getElementById('noResults')?.remove();
                }}
            }}, 300);
        }});
        
        // Security risk chart
        {"" if security_alerts == 0 else f'''
        const ctx = document.getElementById('riskChart');
        if (ctx) {{
            new Chart(ctx, {{
                type: 'doughnut',
                data: {{
                    labels: ['Critical', 'High', 'Medium', 'Low'],
                    datasets: [{{
                        data: [
                            {security_summary.get('critical', 0)},
                            {security_summary.get('high', 0)},
                            {security_summary.get('medium', 0)},
                            {security_summary.get('low', 0)}
                        ],
                        backgroundColor: [
                            '#eb3349',
                            '#f093fb',
                            '#4facfe',
                            '#a8b2d1'
                        ],
                        borderWidth: 0,
                        hoverOffset: 20
                    }}]
                }},
                options: {{
                    responsive: true,
                    plugins: {{
                        legend: {{
                            position: 'bottom'
                        }},
                        title: {{
                            display: true,
                            text: 'Security Risk Distribution'
                        }}
                    }}
                }}
            }});
        }}
        '''}
        
        // Smooth scroll
        document.querySelectorAll('a[href^="#"]').forEach(anchor => {{
            anchor.addEventListener('click', function (e) {{
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                if (target) {{
                    target.scrollIntoView({{ behavior: 'smooth' }});
                }}
            }});
        }});
    </script>
</body>
</html>
"""
        
        return html
    
    def generate_summary_text(self, results: Dict) -> str:
        """
        Generate a quick text summary for console output
        
        Args:
            results: Results dictionary
            
        Returns:
            Text summary
        """
        lines = []
        lines.append("="*60)
        lines.append("RESEARCH SUMMARY")
        lines.append("="*60)
        
        lines.append(f"Task: {results.get('task', 'N/A')}")
        lines.append(f"Agents: {', '.join(results.get('agents_used', []))}")
        
        data = results.get('data', {})
        
        if 'research' in data:
            lines.append(f"\nResearch:")
            lines.append(f"  - Sources: {data['research'].get('sources_scraped', 0)}")
            lines.append(f"  - Items: {data['research'].get('content_items', 0)}")
        
        if 'security' in data:
            lines.append(f"\nSecurity:")
            lines.append(f"  - Alerts: {data['security'].get('alerts', 0)}")
            summary = data['security'].get('summary', {})
            if summary:
                lines.append(f"  - Critical: {summary.get('critical', 0)}")
                lines.append(f"  - High: {summary.get('high', 0)}")
                lines.append(f"  - Medium: {summary.get('medium', 0)}")
        
        lines.append("="*60)
        
        return '\n'.join(lines)


if __name__ == "__main__":
    # Test the report generator
    sample_results = {
        'task': 'https://example.com',
        'timestamp': datetime.now().isoformat(),
        'summary': 'Researched 10 sources',
        'agents_used': ['Web Research Agent'],
        'data': {
            'research': {
                'sources_scraped': 10,
                'content_items': 10
            }
        },
        'raw_results': {
            'web_research': {
                'content': [
                    {
                        'title': 'Example Page',
                        'url': 'https://example.com',
                        'content': 'Sample content',
                        'status_code': 200
                    }
                ],
                'summary': 'Successfully scraped example site'
            }
        }
    }
    
    generator = ReportGenerator()
    report_path = generator.generate_markdown_report(sample_results)
    print(f"Test report generated: {report_path}")
